import '../styles/globals.css'
import Link from 'next/link'
import Head from 'next/head'
import Footer from './components/Footer/Footer'
import { MoralisProvider } from "react-moralis"
import { ServerUrl, AppId } from "../config"

function MyApp({ Component, pageProps }) {
  return (
    <MoralisProvider appId={AppId} serverUrl={ServerUrl}>
      <div className='flex flex-col h-screen'>
        <Head>
          <title> Certified-Cliché</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav className="border-b p-6 place-content-center">
          <p className="text-4xl font-bold mt-4  ">
            Certified-Cliché
          </p>
          <div className="flex mt-4">
            <Link href="/home">
              <a className="mr-4 text-pink-500">
                Home
              </a>
            </Link>
            <Link href="/create-certificate">
              <a className="mr-6 text-pink-500">
                Create Certificate
              </a>
            </Link>
            <Link href="/transferred-certificate">
              <a className="mr-6 text-pink-500">
                Transferred Certificate
              </a>
            </Link>
            <Link href="/my-certificates">
              <a className="mr-6 text-pink-500">
                My Certificates
              </a>
            </Link>
          </div>
        </nav>

        <Component {...pageProps} />
        <Footer />
      </div>
    </MoralisProvider>
  )
}

export default MyApp